# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=NextContent

--NextContent
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--NextContent--

###

# @name create-transcription
POST http://localhost:3333/videos/3a9b59c1-5160-4d7d-8bdb-038ae6bbc62b/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "3a9b59c1-5160-4d7d-8bdb-038ae6bbc62b",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}